name: Release Creation

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build the changelog
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/configs/release-changelog-builder-action.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Change the update file
      - name: Append changelog to file
        id: check_append
        run: |
          echo "Checking and appending changelog to file if new"
          changelog_content="${{ steps.build_changelog.outputs.changelog }}\n"
          current_date=$(date -u +"%Y-%m-%d %H:%M:%S")
          new_entry=$(cat <<EOF
          # $current_date
          $changelog_content
          EOF
          )

          # Generate hash of the new changelog content
          new_entry_hash=$(echo "$new_entry" | sha256sum)

          # Generate hash of the existing file content
          file_hash=$(cat docs/updates.txt | sha256sum)

          # Compare the hashes and append if they are different
          if [ "$new_entry_hash" != "$file_hash" ]; then
            echo "$new_entry" | cat - docs/updates.txt > temp && mv temp docs/updates.txt
            echo "new_changes=true" >> $GITHUB_ENV
          else
            echo "No new changelog content to append."
            echo "new_changes=false" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.new_changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/updates.txt
          git commit -m 'Update updates.txt'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
