name: Release Creation

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build the changelog
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/configs/release-changelog-builder-action.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Change the update file
      - name: Append changelog to file
        run: |
          echo "Prepending changelog to file with date and time"
          changelog_content="${{ steps.build_changelog.outputs.changelog }}"
          current_date=$(date -u +"%Y-%m-%d %H:%M:%S")
          echo -e "\n# $current_date\n$changelog_content\n" | cat - docs/updates.txt > temp && mv temp docs/updates.txt

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/updates.txt
          git commit -m 'Update updates.txt'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
